<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BancoFebrabanSeeder extends Seeder
{
    public function run(): void
    {
        $bancos = [
            ['001', 'Banco do Brasil S.A.'],
            ['003', 'Banco da Amazônia S.A.'],
            ['004', 'Banco do Nordeste do Brasil S.A.'],
            ['007', 'Banco Nacional de Desenvolvimento Econômico e Social'],
            ['012', 'Banco Inbursa S.A.'],
            ['021', 'Banestes S.A. Banco do Estado do Espírito Santo'],
            ['024', 'Banco de Pernambuco S.A. BANDEPE'],
            ['025', 'Banco Alfa S.A.'],
            ['029', 'Banco Itaú Consignado S.A.'],
            ['033', 'Banco Santander Brasil S.A.'],
            ['036', 'Banco Bradesco BBI S.A.'],
            ['037', 'Banco do Estado do Pará S.A. Banpará'],
            ['040', 'Banco Cargill S.A.'],
            ['041', 'Banco do Estado do Rio Grande do Sul S.A. Banrisul'],
            ['047', 'Banco do Estado de Sergipe S.A. Banese'],
            ['062', 'Hipercard Banco Múltiplo S.A.'],
            ['063', 'Banco Bradescard S.A.'],
            ['065', 'Banco Andbank Brasil S.A.'],
            ['066', 'Banco Morgan Stanley S.A.'],
            ['070', 'Banco de la Nación Argentina'],
            ['074', 'Banco Credit Suisse Brasil S.A.'],
            ['075', 'Banco ABN AMRO Real S.A.'],
            ['084', 'Banco do Estado do Rio Grande do Norte S.A.'],
            ['085', 'Banco Fator S.A.'],
            ['094', 'Banco Finasa S.A.'],
            ['097', 'Banco da Providência S.A.'],
            ['104', 'Caixa Econômica Federal'],
            ['107', 'Banco Bocom BBM S.A.'],
            ['108', 'Banco BTG Pactual S.A.'],
            ['113', 'Banco Central do Brasil'],
            ['121', 'Banco Agibank S.A.'],
            ['136', 'Banco Unicred Norte S.A.'],
            ['151', 'Banco Unicred Norte S.A.'],
            ['184', 'Banco Matone S.A.'],
            ['189', 'Banco Bradesco Financiamentos S.A.'],
            ['190', 'Banco Alvorada S.A.'],
            ['194', 'Banco Itau BBA S.A.'],
            ['208', 'Banco BTG Pactual S.A.'],
            ['212', 'Banco Original do Brasil S.A.'],
            ['213', 'Banco Inter S.A.'],
            ['218', 'Banco BS2 S.A.'],
            ['222', 'Banco Credit Agricole Brasil S.A.'],
            ['224', 'Banco Fibra S.A.'],
            ['225', 'Banco Brascan S.A.'],
            ['229', 'Banco Cruzeiro do Sul S.A.'],
            ['230', 'Banco Votorantim S.A.'],
            ['233', 'Banco Cifra S.A.'],
            ['237', 'Banco Bradesco S.A.'],
            ['241', 'Banco Clássico S.A.'],
            ['243', 'Banco Master S.A.'],
            ['246', 'Banco ABC Brasil S.A.'],
            ['249', 'Banco Investcred Unibanco S.A.'],
            ['250', 'Banco KDB Brasil S.A.'],
            ['254', 'Paraná Banco S.A.'],
            ['260', 'Nu Pagamentos S.A. Nubank'],
            ['265', 'Banco Fator S.A.'],
            ['269', 'Banco HSBC S.A.'],
            ['272', 'Banco Digibank S.A.'],
            ['274', 'Banco Paulista S.A.'],
            ['277', 'Banco Bocom BBM S.A.'],
            ['280', 'Avista S.A. Crédito Financiamento e Investimento'],
            ['281', 'Cooperativa de Crédito Rural Coopavel'],
            ['289', 'Decyseo Corretora de Câmbio Ltda.'],
            ['290', 'PagSeguro Internet S.A.'],
            ['291', 'Banco Credit Suisse Brasil S.A.'],
            ['299', 'Banco Afinz S.A. Banco Múltiplo'],
            ['318', 'Banco BMG S.A.'],
            ['320', 'Bank of China Brasil Banco Múltiplo S.A.'],
            ['336', 'Banco C6 S.A.'],
            ['341', 'Itaú Unibanco S.A.'],
            ['347', 'Banco Rendimento S.A.'],
            ['348', 'Banco XP S.A.'],
            ['353', 'Banco Safra S.A.'],
            ['389', 'Banco Mercantil do Brasil S.A.'],
            ['412', 'Banco Capital S.A.'],
            ['422', 'Banco Safra S.A.'],
            ['456', 'Banco Raiz S.A.'],
            ['477', 'Banco Svida S.A.'],
            ['505', 'Banco Citibank S.A.'],
            ['548', 'Banco Intercap S.A.'],
            ['610', 'Banco A. J. Renner S.A.'],
            ['613', 'Banco Pan S.A.'],
            ['622', 'Banco Pan S.A.'],
            ['623', 'Banco Pan S.A.'],
            ['626', 'Banco Fator S.A.'],
            ['630', 'Banco Smartbank S.A.'],
            ['653', 'Banco Indusval S.A.'],
            ['654', 'Banco A.J. Renner S.A.'],
            ['655', 'Banco Votorantim S.A.'],
            ['707', 'Banco Daycoval S.A.'],
            ['748', 'Banco Cooperativo Sicredi S.A.'],
            ['751', 'Scotiabank Brasil Banco Múltiplo S.A.'],
            ['752', 'Banco BNP Paribas Brasil S.A.'],
            ['753', 'Banco Sistema S.A.'],
            ['754', 'Banco Sistema S.A.'],
            ['756', 'Banco Cooperativo Central de Crédito Sicoob S.A.'],
        ];

        DB::table('banco_febrabans')->insertOrIgnore(
            collect($bancos)->map(fn($banco) => [
                'codigo' => $banco[0],
                'nome' => $banco[1],
                'ativo' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ])->toArray()
        );
    }
}
